volumes:
  basket-mssql-data:

services:
  basket-service:
    container_name: basket-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - basket-mssql-db
    ports:
      - 8005:8080
    environment:
      - MIGRATE_DATABASE=true
      - ConnectionStrings__BasketDb=Server=basket-mssql-db,1433;Database=BasketDb;User Id=sa;Password=Super.secretpa55word;TrustServerCertificate=True;
  basket-mssql-db:
    container_name: basket-mssql-db
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1439:1433
    volumes:
      - basket-mssql-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: Super.secretpa55word
