volumes:
  order-mssql-data:

services:
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - order-mssql-db
    ports:
      - 8004:8080
    environment:
      ConnectionStrings__OrderDb: "Server=order-mssql-db,1433;Database=OrderDb;User Id=sa;Password=Super.secretpa55word;TrustServerCertificate=True;"
  
  order-mssql-db:
    container_name: order-mssql-db
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1438:1433
    volumes:
      - order-mssql-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: Super.secretpa55word