FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Payment.Api/Payment.Api.csproj", "Payment.Api/"]
COPY ["Payment.Core/Payment.Core.csproj", "Payment.Core/"]
COPY ["Payment.Infrastructure/Payment.Infrastructure.csproj", "Payment.Infrastructure/"]

RUN dotnet restore "Payment.Api/Payment.Api.csproj"

COPY . .

WORKDIR "/src/Payment.Api"

ARG CONFIGURATION=Release

RUN dotnet build "Payment.Api.csproj" -c $CONFIGURATION -o /app/build

RUN dotnet publish "Payment.Api.csproj" -c $CONFIGURATION -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["dotnet", "Payment.Api.dll"]