volumes:
  inventory-mssql-data:

services:
  
  inventory-service:
    container_name: inventory-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - inventory-mssql-db
    ports:
      - 8003:8080
    environment:
      ConnectionStrings__InventoryDb: "Server=inventory-mssql-db,1433;Database=InventoryDb;User Id=sa;Password=Super.secretpa55word;TrustServerCertificate=True;"

  inventory-mssql-db:
    container_name: inventory-mssql-db
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    cap_add: [ 'SYS_PTRACE' ]
    user: root
    ports:
      - 1437:1433
    volumes:
      - inventory-mssql-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: y
      MSSQL_SA_PASSWORD: Super.secretpa55word