// <auto-generated />
using Inventory.Infrastructure.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Core.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("int");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("int");

                    b.Property<int>("ShippedCount")
                        .HasColumnType("int");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogItemId = 1,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 2,
                            CatalogItemId = 2,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 3,
                            CatalogItemId = 3,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 4,
                            CatalogItemId = 4,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 5,
                            CatalogItemId = 5,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 6,
                            CatalogItemId = 6,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 7,
                            CatalogItemId = 7,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 8,
                            CatalogItemId = 8,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 9,
                            CatalogItemId = 9,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 10,
                            CatalogItemId = 10,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 11,
                            CatalogItemId = 11,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        },
                        new
                        {
                            Id = 12,
                            CatalogItemId = 12,
                            ReservedCount = 0,
                            ShippedCount = 0,
                            StockCount = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
